### ISSUE TITLE
Reporting stream error in kinesis_video_streamer

### ISSUE THREAD

**Issue by VRichardJP** [aws-robotics/kinesisvideo-ros1#52] opened 2020-09-30 07:39 UTC
Hi,

I would like to send ROS images to AWS. I have first checked the [WebRTC C SDK](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-c.html) and managed to send a video sample to a KVS channel
I would like to do the same but with ROS data, which seems to be exactly what this repository is for. However I don't understand how to use setup it properly.

The ROS image data is published on topic /image_raw. Using h264_video_encoder package, I encode these messages to KVS format and publish them to /image_raw/encoded.

However when I try to run kinesis_video_streamer.launch to send the encoded data to AWS, it fails with the following error:
```
roslaunch kinesis_video_streamer kinesis_video_streamer.launch node_config_file:=config/kvs_node_config.yaml stream_config_file:=config/kvs_stream_config.yaml
... logging to /home/vrichard/.ros/log/28c6c7b6-02e9-11eb-9c5c-d45d6451c78d/roslaunch-vr-desktop-18357.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vr-desktop:43195/

SUMMARY
========

PARAMETERS
 * /kinesis_video_streamer/aws_client_configuration/connect_timeout_ms: 9000
 * /kinesis_video_streamer/aws_client_configuration/max_retries: 10
 * /kinesis_video_streamer/aws_client_configuration/region: ap-northeast-1
 * /kinesis_video_streamer/aws_client_configuration/request_timeout_ms: 9000
 * /kinesis_video_streamer/kinesis_video/log4cplus_config: /home/vrichard/aw...
 * /kinesis_video_streamer/kinesis_video/stream0/frame_rate: 30
 * /kinesis_video_streamer/kinesis_video/stream0/frame_timecodes: False
 * /kinesis_video_streamer/kinesis_video/stream0/stream_name: Channel-1
 * /kinesis_video_streamer/kinesis_video/stream0/subscription_topic: /image_raw/encoded
 * /kinesis_video_streamer/kinesis_video/stream0/topic_type: 1
 * /kinesis_video_streamer/kinesis_video/stream_count: 1
 * /rosdistro: melodic
 * /rosversion: 1.14.9

NODES
  /
    kinesis_video_streamer (kinesis_video_streamer/kinesis_video_streamer)

ROS_MASTER_URI=http://localhost:11311

process[kinesis_video_streamer-1]: started with pid [18384]
[ERROR] [1601449079.952187336]: [streamErrorReportHandler] Reporting stream error. Errored timecode: 0 Status: 1375731728
[ERROR] [1601449109.843852886]: [KinesisVideoStreamSetup] Skipping stream id 0 due to failure initializing stream. Error code: 4100
Failed to setup the kinesis video streamer[ERROR] [1601449109.843964114]: [InitializeStreamSubscriptions] KinesisVideoStreamerSetup failed with error code : 4096. Exiting
[kinesis_video_streamer-1] process has finished cleanly
log file: /home/vrichard/.ros/log/28c6c7b6-02e9-11eb-9c5c-d45d6451c78d/kinesis_video_streamer-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

The configuration I am using is:
- kvs_node_config.yaml:
```
aws_client_configuration:
  region: "ap-northeast-1"
  connect_timeout_ms: 9000
  request_timeout_ms: 9000
  max_retries: 10
```
- kv_stream_config.yaml:
```
stream_name: "Channel-1"
subscription_topic: /image_raw/encoded
topic_type: 1
frame_rate: 30
frame_timecodes: false
```

Am I missing something in the configuration?

**Comment by dabonnie** [comment] 2020-10-06 00:42
Hi @VRichardJP , thanks for reporting your issue: I'm currently looking into your error codes. Could you please share your `h264_video_encoder` configuration details as well?

**Comment by VRichardJP** [comment] 2020-10-06 01:01
I use the following file:
```
subscription_topic: "/image_raw"
publication_topic: "/image_raw/encoded"
fps_numerator: 30
fps_denominator: 1
bitrate: 2048000
```
and start the node with:
```
roslaunch h264_video_encoder h264_video_encoder.launch config_file:=config/h264_video_encoder_config.yaml output:=screen image_transport:=raw
```
I can see the messages are published with rostopic tool.

**Comment by dabonnie** [comment] 2020-10-06 23:34
Hi @VRichardJP, thanks for providing all of your configuration details. I've been able to reproduce your issue (using a simple publisher sending images to the `h264_video_encoder` and observe the same error:

```
[ERROR] [1602026841.310674433]: [streamErrorReportHandler] Reporting stream error. Errored timecode: 0 Status: 1375731728
[ERROR] [1602026871.210216341]: [KinesisVideoStreamSetup] Skipping stream id 0 due to failure initializing stream. Error code: 4100
```

I'll keep investigating to see if there is a bug.

**Comment by mhaboali** [comment] 2020-10-07 11:25
Hi 

I'm trying to do the same here but I didn't get the same error and here's my log:
```
NODES
  /
    h264_video_encoder (h264_video_encoder/h264_video_encoder)
    kinesis_video_streamer (kinesis_video_streamer/kinesis_video_streamer)

ROS_MASTER_URI=http://localhost:11311

process[kinesis_video_streamer-1]: started with pid [1066]
process[h264_video_encoder-2]: started with pid [1067]
[h264_omx @ 0x55b308c6ce00] libOMX_Core.so not found
[h264_omx @ 0x55b308c6ce00] libOmxCore.so not found
[ERROR] [1602069600.426367174]: [open_codec] Could not open codec
[libx264 @ 0x55b308c6ce00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x55b308c6ce00] profile High, level 2.2
[libx264 @ 0x55b308c6ce00] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=1 keyint=4 keyint_min=3 scenecut=40 intra_refresh=0 rc=abr mbtree=0 bitrate=2048 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[ WARN] [1602069601.400169095]: [KinesisVideoFrameTransportCallback] lunrbot_stream PutFrame failed. Error code: 4102
[ WARN] [1602069601.400309385]: [KinesisVideoFrameTransportCallback] lunrbot_stream PutFrame failed. Error code: 4102
[ WARN] [1602069601.400381187]: [KinesisVideoFrameTransportCallback] lunrbot_stream PutFrame failed. Error code: 4102
[ WARN] [1602069601.400473216]: [KinesisVideoFrameTransportCallback] lunrbot_stream PutFrame failed. Error code: 4102
[ WARN] [1602069601.400547154]: [KinesisVideoFrameTransportCallback] lunrbot_stream PutFrame failed. Error code: 4102
[ WARN] [1602069601.501035909]: [KinesisVideoFrameTransportCallback] lunrbot_stream PutFrame failed. Error code: 4102
```
And I didn't receive anything on the client viewer on the AWS Kinesis Signaling stream.

In spite of those warnings/errors, it looks normal because I got the same log with the normal Kinesis video stream and it was working on the AWS dashboard 

Thanks for your help @dabonnie

**Comment by dabonnie** [comment] 2020-10-07 22:25
@VRichardJP my mistake, did you export your credentials?

`[ERROR] [1601449079.952187336]: [streamErrorReportHandler] Reporting stream error. Errored timecode: 0 Status: 1375731728`

Status code `1375731728` is `0x52000010`, which means

>0x52000010 | STATUS_SERVICE_CALL_NOT_AUTHORIZED_ERROR | Not authorized.

https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-errors.html

Please see [this README section](https://github.com/aws-robotics/kinesisvideo-ros1#aws-credentials) concerning credentials. 

---

@mhaboali thanks for the info, I'm attemping to reproduce your issue. A few questions:

* what's the platform?
* what kind of data are you attempting to stream?
* can you share the node configurations?

**Comment by mhaboali** [comment] 2020-10-08 06:14
Have you sent ROS images to Kinesis Signaling(WebRTC) channel? I'm able to send ROS images to Kinesis Video Stream on a normal channel(not WebRTC) but I have around 4 seconds latency which's not acceptable for the application.

**Comment by mhaboali** [comment] 2020-10-08 06:20
And regarding the platform, I'm using kubuntu image into a VM machine and the configurations are exactly the same like the examples. As mentioned, I managed to get the images to a Video Stream not signaling channel.

**Comment by dabonnie** [comment] 2020-10-08 18:34
> Thanks, @dabonnie for your support!
> 
> Have you sent ROS images to Kinesis Signaling(WebRTC) channel? I'm able to send ROS images to Kinesis Video Stream on a normal channel(not WebRTC) but I have around 4 seconds latency which's not acceptable for the application.

Thank you for the details and clarification. Currently, the `kinesisvideo-ros1` does not support sending data to the  Kinesis Signaling(WebRTC) channel.

**Comment by VRichardJP** [comment] 2020-10-09 01:44
@dabonnie 
Well if it is not supported no wonder it was not working ;)

I managed to do make it work with the C SDK sample [kvsWebRTCClientMaster.c](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c). I did the following:
- changed the sample main to be an init function
- Implemented a small ros node that init the client and subscribe to the KVS frame topic (I still use the h264 node to do this)
- moved the sessionCleanUpWait logic into the node spin loop code
- removed all the thread/cvar/sendVideoFrame/sendAudioFrame/readFrameFromDisk/Timer/... from the sample since ros does everything
- used [this comment](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/423#issuecomment-624391299) to convert KVS ROS frame to C Frame in the ros image callback function

**Comment by mhaboali** [comment] 2020-10-09 05:59
Thanks, @VRichardJP a lot for your guidance!

I'm trying to do it right now and hopefully, I'll be able to get it working. I'll keep you posted on my status.

Thanks!

**Comment by dabonnie** [comment] 2020-10-12 23:51
@VRichardJP glad you were able to find a path forward. Unless there are any other questions I'm going to close this issue (feel free to re-open with anything new).

**Closed by dabonnie** 2020-10-12 23:51 UTC
Labels: question

**Comment by juanea** [comment] 2021-01-26 05:32
@VRichardJP Thanks for this.
When you say that you:
- moved the sessionCleanUpWait logic into the node spin loop code
- removed all the thread/cvar/sendVideoFrame/sendAudioFrame/readFrameFromDisk/Timer/... from the sample since ros does everything
Could you please explain?
Thank you

**Comment by VRichardJP** [comment] 2021-01-26 14:03
I don't have the code under my eyes, but from memory:
- sessionCleanUpWait in the kvs sample is a loop that simply wait for the reader threads to have finished processing the frames from disk. With ros we don't read frames from the disk but subscribe to the topic to which encoded frames are published. So basically, you need to take the content of sessionCleanUpWait and keep what is relevant into your ros main loop.
- thread, cvar and other synchronization variables are useless with ros framework. For instance, instead of starting a reader thread to process frames, we simply subscribe to the encoded frames topic and put the processing logic in a callback. Everything can be written asynchronously without thread, hence we can get rid of threads and synchronization mechanisms.

**Comment by pavloblindnology** [comment] 2021-01-26 15:21
Any will to PR-st your changes? Streaming to WebRTC with H264 seems to be the main goal of the package, but it's not supported. Which is strange at least.
> I don't have the code under my eyes, but from memory:
> 
> * sessionCleanUpWait in the kvs sample is a loop that simply wait for the reader threads to have finished processing the frames from disk. With ros we don't read frames from the disk but subscribe to the topic to which encoded frames are published. So basically, you need to take the content of sessionCleanUpWait and keep what is relevant into your ros main loop.
> * thread, cvar and other synchronization variables are useless with ros framework. For instance, instead of starting a reader thread to process frames, we simply subscribe to the encoded frames topic and put the processing logic in a callback. Everything can be written asynchronously without thread, hence we can get rid of threads and synchronization mechanisms.

**Comment by juanea** [comment] 2021-01-26 18:40
Thank you @VRichardJP
